require 'vagrant-azure'

Vagrant.configure("2") do |config|

  config.vm.box = "azure"
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  # Configuramos las diferentes maquinas
  config.vm.define "maquina1" do |maquina1|
    maquina1.vm.hostname = "maquinaservicio"

    maquina1.vm.provider "azure" do |az|  # Parametros para AZURE
      # Variables de entorno
      az.tenant_id = ENV['AZURE_TENANT_ID']
      az.client_id = ENV['AZURE_CLIENT_ID']
      az.client_secret = ENV['AZURE_CLIENT_SECRET']
      az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

      # Datos para la MV
      az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
      az.vm_name = 'maquinaservicio'
      az.admin_username = "andreamg"
      az.vm_size = 'Standard_B1s' # dejo esta de momento porque Basic_A0 va muy lenta
      az.resource_group_name = 'resourcegrouphito5'
      az.location = 'francecentral'
      az.tcp_endpoints = [80,27017]
      az.virtual_network_name = "andreanetwork"
    end

    # Copiamos en la máquina solo los ficheros que nos hacen falta para ejecutar la app
    maquina1.vm.provision "file", source: "../app_flask.py", destination: "/home/vagrant/ProyectoCC/app_flask.py"
    maquina1.vm.provision "file", source: "../predictionDB.py", destination: "/home/vagrant/ProyectoCC/predictionDB.py"
    maquina1.vm.provision "file", source: "../weather_class.py", destination: "/home/vagrant/ProyectoCC/weather_class.py"
    maquina1.vm.provision "file", source: "../requirements.txt", destination: "/home/vagrant/ProyectoCC/requirements.txt"


    maquina1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end

    # Añadido para tener la variable de entorno que buscamos en la máquina, y así no tener que meterla nosotros manualmente
    # maquina1.vm.provision "shell", inline: "echo "export IP='10.0.0.4'" >> .bashrc", run: "always"


  end

  config.vm.define "maquina2" do |maquina2|

    maquina2.vm.hostname = "maquinamongo"
    maquina2.vm.provider "azure" do |az|  # Parametros para AZURE
    # Variables de entorno
    az.tenant_id = ENV['AZURE_TENANT_ID']
    az.client_id = ENV['AZURE_CLIENT_ID']
    az.client_secret = ENV['AZURE_CLIENT_SECRET']
    az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Datos para la MV
    az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
    az.vm_name = 'maquinamongo'
    az.vm_size = 'Standard_B1s'
    az.admin_username = "andreamg"
    az.resource_group_name = 'resourcegrouphito5'
    az.location = 'francecentral'
    az.tcp_endpoints = [80,27017]
    az.virtual_network_name = "andreanetwork"
    end

    maquina2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-mongodb.yml"
    end

  end


end
